CREATE TABLE vehicle_document (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL REFERENCES vehicle (id) ON DELETE CASCADE,
    type       VARCHAR(30) NOT NULL,
    status     VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    expires_on DATE,
    UNIQUE (vehicle_id, type)
);
